"use strict";
exports.__esModule = true;
exports.Some = function (value) { return [true, value]; };
exports.None = function () { return [false, null]; };
exports.isSome = function (maybe) { return maybe[0]; };
exports.isNone = function (maybe) { return !maybe[0]; };
exports.map = function (fn) { return function (maybe) { return exports.isSome(maybe) ? exports.Some(fn(maybe[1])) : maybe; }; };
exports.andThen = function (fn) { return function (maybe) { return exports.isSome(maybe) ? fn(maybe[1]) : maybe; }; };
exports.withDefault = function (fallback) { return function (maybe) { return exports.isSome(maybe) ? maybe[1] : fallback; }; };
exports.unwrap = function (some) { return some[1]; };
